# Generated by Django 5.1.3 on 2024-11-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50)),
                ("stamp_count", models.IntegerField()),
                ("store_count", models.IntegerField()),
                ("tour_count", models.IntegerField()),
                ("secret_count", models.IntegerField()),
            ],
        ),
    ]
