# Generated by Django 5.1.3 on 2024-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AR_DATA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField()),
                ("tour_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="stamp_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField()),
                ("tour_id", models.CharField(max_length=50)),
                ("num", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Tour_place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_id", models.IntegerField()),
                ("place", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("lat", models.CharField(max_length=50)),
                ("lng", models.CharField(max_length=50)),
                ("text", models.CharField(max_length=1000)),
            ],
        ),
    ]
